'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar';
import Colecciones from '@/components/colecciones';
import Carousel from '@/components/carousel';

const inter = Inter({ subsets: ['latin'] });

//export const metadata = {
//title: 'Luna Mora',
//description: 'Generated by create next app',
//};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Puedes agregar aquí tus etiquetas <meta>, <link>, etc., según sea necesario */}
      </head>
      <body className={inter.className}>
        <Navbar />
        <Carousel />
        <Colecciones />
        {children}

      </body>
    </html>
  );
}

RootLayout.useClient = true;
export default RootLayout;
