'use client';
import '../styles/globals.css';
import {
  Roboto_Condensed, Alex_Brush
} from 'next/font/google';
import Navbar from '@/components/navbar';
import Colecciones from '@/components/colecciones';
import Carousel from '@/components/carousel';

const roboto = Roboto_Condensed({
  weight: ["300"],
  style: ["normal"],
  subsets: ["latin"],
})
const alex = Alex_Brush({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
})

//export const metadata = {
//title: 'Luna Mora',
//description: 'Generated by create next app',
//};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Puedes agregar aquí tus etiquetas <meta>, <link>, etc., según sea necesario */}
      </head>
      <body className={roboto.className}>
        <Navbar />
        <Carousel />
        <Colecciones />
        {children}

      </body>
    </html>
  );
}

RootLayout.useClient = true;

